Repository archesproject/arches, pull requests merged in 2023-06, with the labels that each got.

#9596 Add Home Link to side navigation menu re. issue #9560
  arches/app/templates/base-manager.htm
Labels: enhancement

#9478 9477 edtf and table alias fix for spatial views
  arches/app/models/migrations/9477_fix_for_spatial_view_dbf_function_edtf_displaying_null.py
  arches/app/models/migrations/9477_fix_for_spatial_view_dbf_function_table_alias_error.py
Labels: bug

#9612 resolves issue with 2 sets of save/discard buttons appearing in some edge cases #9591
  arches/app/media/js/views/graph-designer.js
  arches/app/templates/views/graph-designer.htm
  arches/app/templates/views/graph/graph-designer/node-form.htm
Labels: Type: Bug

#9609 Use I18n for mapping file export #9680
  arches/app/utils/data_management/resource_graphs/exporter.py
Labels: Type: Bug

#9543 9531 Make search help accessible
  arches/app/media/css/arches.scss
  arches/app/media/js/views/page-view.js
  arches/app/templates/help/search-help.htm
Labels: Subject: Accessibility

#9533 9500 Make time filter accessible
  arches/app/media/css/arches.scss
  arches/app/media/css/components/search/_index.scss
  arches/app/media/css/components/search/_time-filter.scss
  arches/app/templates/javascript.htm
  arches/app/templates/views/components/search/time-filter.htm
Labels: Subject: Accessibility

#9532 9497 Make saved search accessible
  arches/app/templates/views/components/search/saved-searches.htm
Labels: Subject: Accessibility

#9611 9541 Make search toolbar accessible
  arches/app/templates/views/search.htm
Labels: Subject: Accessibility

#9513 9494 Make search paging filter accessible
  arches/app/templates/javascript.htm
  arches/app/templates/views/components/search/paging-filter.htm
Labels: Subject: Accessibility

#9509 9496 Make search resource filter accessible
  arches/app/templates/views/components/search/resource-type-filter.htm
Labels: Subject: Accessibility

#9659 9387 Make search results panel accessible
  arches/app/media/css/arches.scss
  arches/app/media/js/utils/aria.js
  arches/app/templates/views/components/search/provisional-filter.htm
  arches/app/templates/views/components/search/resource-type-filter.htm
  arches/app/templates/views/components/search/search-results.htm
  arches/app/templates/views/search.htm
Labels: Subject: Accessibility

#9666 9555 Skip to content link added upon first keyboard tab
  arches/app/media/css/base-manager.css
  arches/app/templates/base-manager.htm
  arches/app/templates/javascript.htm
Labels: Subject: Accessibility

#9467 9347 Make resource instance widget accessible
  arches/app/media/js/viewmodels/resource-instance-select.js
  arches/app/models/models.py
  arches/app/templates/javascript.htm
  arches/app/templates/views/components/datatypes/resource-instance.htm
  arches/app/templates/views/components/widgets/resource-instance-select.htm
  arches/app/utils/permission_backend.py
Labels: Subject: Accessibility

#9489 9348 Make select widget accessible
  arches/app/templates/views/components/widgets/select.htm
Labels: Subject: Accessibility

#9688 9677 Add escape key handler
  arches/app/media/js/utils/aria.js
Labels: Subject: Accessibility
