Repository archesproject/arches, pull requests merged in 2023-11, with the labels that each got.

#10068 9863 Replace homepage slider with a more modern, accessible plugin
  arches/app/media/css/index-slider-legacy.css
  arches/app/media/css/index-slider.css
  arches/app/media/css/index.css
  arches/app/media/plugins/revolution-slider.js
  arches/app/media/plugins/revolution-slider/rs-plugin/css/settings-ie8.css
  arches/app/media/plugins/revolution-slider/rs-plugin/css/settings.css
  arches/app/media/plugins/revolution-slider/rs-plugin/font/revicons.svg
  arches/app/media/plugins/revolution-slider/rs-plugin/js/jquery.themepunch.revolution.js
  arches/app/media/plugins/revolution-slider/rs-plugin/js/jquery.themepunch.revolution.min.js
  arches/app/media/plugins/revolution-slider/rs-plugin/js/jquery.themepunch.tools.min.js
  arches/app/media/plugins/revolution-slider/rs-plugin/js/jquery2.2.3/jquery.min.js
  arches/app/media/plugins/slick/accessible-slick-theme.min.css
  arches/app/media/plugins/slick/accessible-slick-theme.scss
  arches/app/media/plugins/slick/ajax-loader.gif
  arches/app/media/plugins/slick/fonts/slick.eot
  arches/app/media/plugins/slick/fonts/slick.svg
  arches/app/media/plugins/slick/fonts/slick.ttf
  arches/app/media/plugins/slick/fonts/slick.woff
  arches/app/media/plugins/slick/slick-theme.min.css
  arches/app/media/plugins/slick/slick-theme.scss
  arches/app/media/plugins/slick/slick.js
  arches/app/media/plugins/slick/slick.min.css
  arches/app/media/plugins/slick/slick.min.js
  arches/app/media/plugins/slick/slick.scss
  arches/app/templates/index.htm
  arches/install/arches-templates/project_name/templates/index.htm
  package.json
Labels: Subject: Accessibility

#10239 Add missing `{{ block.super }}` to javascript.htm instructions
  releases/7.0.0.md
  releases/7.1.0.md
  releases/7.1.1.md
  releases/7.2.0.md
Labels: Subject: Documentation

#10255 Add search toolbar btn tooltips #10251
  arches/app/templates/views/search.htm
Labels: Subject: Accessibility

#10214 Handle multiple Subcard levels in Search Export. #10199
  arches/app/search/search_export.py
Labels: Type: Bug

#10267 9903 Map filter contrast issue
  arches/app/media/css/accessibility.scss
Labels: Subject: Accessibility

#10271 9761 Ensure reflow of report title and tools
  arches/app/media/css/arches.scss
  arches/app/media/css/pages/_report.scss
Labels: Subject: Accessibility

#10291 9839 Login/logout/welcome message fixes
  arches/app/media/css/arches.scss
  arches/app/templates/base-manager.htm
Labels: Subject: Accessibility
