Repository archesproject/arches, pull requests merged in 2025-03, with the labels that each got.

#11809 Restore ability to join TileModel to NodeGroup via ORM #11808
  arches/app/models/migrations/11726_join_tile_nodegroup.py
  arches/app/models/models.py
  releases/8.0.0.md
  tests/models/tile_model_tests.py
Labels: Subject: Performance

#11858 Spatial view geometrynode validation fixes and v8 filter additions
  arches/app/models/migrations/11857_spatial_view_source_identifier_filter.py
  arches/app/models/models.py
  tests/models/spatialview_model_tests.py
Labels: squash me

#11886 Fix severe performance issue in related resource view #11885
  arches/app/models/resource.py
  pyproject.toml
  releases/7.6.8.md
  tests/views/resource_tests.py
Labels: Subject: Performance, squash me

#11898 Remove sequence scan on tiles from GraphManagerView
  arches/app/views/graph.py
  releases/7.6.8.md
Labels: Subject: Performance
